### ISSUE TITLE
Third party providers

### ISSUE THREAD

**Issue by steffendsommer** [vapor-community/styleguide#11]
Great initiative making this style guide. Our team is looking into adopting these guidelines. 

One thing that I want to bring forward at this point: what is the motivation for having the `-provider` in third party packages? It seems to be a style from Vapor 2 that didn't make it into Vapor 3 and I'm not sure I see the benefits in having this suffix. The guidelines suggest to omit it in the library name and in `Package.swift` we already have the full url indicating where a package is coming from.

**Comment by jdmcd** [comment]
Hey! Glad you’re enjoying the guide and considering adopting it. 

Regarding the providers question, I’d like to ping @Andrewangeta for this as he wrote that section and I want to make sure we include his input as well. I believe the logic behind that section was to help differentiate between packages that provide 3rd-party functionality and packages that provide simple models or framework-level functionality. It’s a great point to bring up and something we should definitely consider before this gets merged into the Vapor docs (see the PR on vapor/documentation).

**Comment by Andrewangeta** [comment]
Yea we had his discussion some time ago when we were on slack and actually had the community vote on the style. Motivation being that it differentiated a third party service as opposed to just a separate module of functionality. A provider more or less is a vapor library for existing API’s like Stripe or google cloud or aws. While the repo name has the `-provider` it’s cleaner in code tohave the module or `import` statement to have the providers name itself like `import AWS`

**Comment by steffendsommer** [comment]
@Andrewangeta so that means that it's not the presence of a `Provider` in your library, but more what your library wraps that dictates if it's a provider or not? E.g.:

- I make a library that wraps Firebase = Provider
- I make a library for handling everything related to auth = Not a provider (since it's not wrapping existing API's)

Is that correctly understood?

**Comment by Andrewangeta** [comment]
Correct @steffendsommer 👍

**Comment by steffendsommer** [comment]
@Andrewangeta I apologise for the delayed reply. I would suggest that we remove this convention due to the following reasons:

- I think it becomes hard to communicate when to use the suffix or not. We strive for consistency, so we might as well keep it simple and precise.
- There could be some cases where one library has been fulfilling the requirements for being a provider but not anymore. In those cases, it would great not having to have to rename it (although GitHub makes this easy for you).
- Who does this suffix add value to? The consumer? If the definition is vague, then there might be trust issues, leaving people to go through the readme (which they might do anyways). In other words, maybe it should be up to the readme to communicate what the library offers?

These are just some thoughts on the top of my head. We had this convention at some point but started to omit it for simplicity. What do you guys think?

**Comment by jdmcd** [comment]
I like your third point - I think the readme and docs for the package should properly explain what it does. Especially since the `provider` suffix is removed for imports and any actual usage of the library. @Andrewangeta what do you think?

**Comment by Andrewangeta** [comment]
If we’re looking at removing the provider suffix I think it makes sense to remove it altogether in Vapor itself. Vapor has a `Provider` type that gets registered. If the suffix isn’t adding much value per say, does it make sense to remove it altogether? @tanner0101 thoughts on this?

**Comment by jdmcd** [comment]
I think the `Provider` type adds a lot of value in terms of being able to register multiple services as an abstraction (often presented as a library). From my vantage point it seems like this conversation is mostly revolving around the actual naming of those packages since they tend to provide more functionality than just offering a `Provider`. Does that make sense/am I off-base?

**Comment by steffendsommer** [comment]
@mcdappdev I agree

**Comment by Andrewangeta** [comment]
I think from visibility seeing the `-provider` extension in a repo from the `vapor-community` org makes it easier to know what I'm getting into. I'm assuming that people generally know what to expect when they see something like `firebase-provider` or `stripe-provider`. If anything since you made a good point about a `Provider` offering services, a package should be probably be named `my-provider` and any general library etc. could drop that suffix. Idk I think it just makes sense and it's easier to reason about looking through the repo names. It also sets a certain expectation because mainly this is about packages that will be hosted in the `vapor-community` org.

**Comment by jdmcd** [comment]
I think that if the reasoning is cosmetic in terms of an accessibility standard then an argument could also be made that the GH description and tags could replace that convention as well. It’s kinda a moot point in things like Package.swift since you should probably know what that library does at that point and you can assume it provides the functionality of its name.

**Comment by Andrewangeta** [comment]
I see your point, also with the tags I know in the docs there's a tag for `vapor-service` that links to all available plugins/providers/services.

**Comment by steffendsommer** [comment]
@mcdappdev @Andrewangeta what are your thoughts on this? Do you want to keep it as it is or are you interested in updating it? If so, should I make a PR for it?

**Comment by jdmcd** [comment]
I think we should remove the provider suffix. There’s currently a PR open on Vapor/Documentation, could you make a PR here with the changes you want to see, we can discuss, and then I’ll move it over there?

**Comment by Andrewangeta** [comment]
Yea I think it’s shouldn’t be a requirement to have the suffix. But at least for repos I maintain I’ll keep the suffix out of convenience of readability. 👍

**Comment by jdmcd** [comment]
Works for me!

**Comment by jdmcd** [comment]
@steffendsommer @Andrewangeta Can you review this change, please? https://github.com/vapor/documentation/pull/347/commits/8532899e7c6f96d6278d668e65e2efb45eae3962 Want to make sure I didn't miss anything in our conversation.

**Comment by steffendsommer** [comment]
@mcdappdev LGTM 👍

**Comment by jdmcd** [comment]
Perfect, thanks!
